### ISSUE TITLE
dice_average

### ISSUE THREAD

**Issue by xuexuezhouzhou** [AngeLouCN/CaraNet#1]
hello,I want to ask if dice_average code is correct?

**Comment by ShuyueG** [comment]
It is correct. _Note:_ the arrays AreaR and Dice should have the **same length**. For i-th case, AreaR(i) is the area ratio (see code comments for its computation) of objects in the image of i-th segmented ground truth (the binary label), Dice(i) is the Dice coefficient computed by using the i-th predicted segmentation result and its ground truth. bin_width depends on the distribution of AreaR.
