### ISSUE TITLE
About the CaraNet.py

### ISSUE THREAD

**Issue by 15104356116** [AngeLouCN/CaraNet#10]
Thanks for your code! But I still can not figure what  `cfpnet_res2net_v4 () ` is. This code is on line 135 of CaraNet.py.

**Comment by AngeLouCN** [comment]
Hi, it should be the caranet(). However, it will not affect the use of code and I will fix it soon.

**Comment by 15104356116** [comment]
Sorry to bother you again. Here is my result. And I would like to know how can I optimize the results.
Here are two sets of result, mask and image.
![Ty20180910_1_1](https://user-images.githubusercontent.com/67885785/148674904-78cc1bc4-0c27-4721-8c38-b983090b8a37.png)
![Ty20180910_1_1](https://user-images.githubusercontent.com/67885785/148674941-ed7f56ac-1d4e-425a-8fa1-b516e5e085c9.png)
![Ty20180910_1_1](https://user-images.githubusercontent.com/67885785/148674926-a757ceb3-42ed-424a-9fc1-f9ef8ccc29a8.png)
![Ty20180910_3_7](https://user-images.githubusercontent.com/67885785/148674959-a03feaec-de15-4406-b195-b40ce29e0c59.png)
![Ty20180910_3_7](https://user-images.githubusercontent.com/67885785/148674977-2a2701d7-e75f-4096-b2ff-fcf5adb41ea7.png)
![Ty20180910_3_7](https://user-images.githubusercontent.com/67885785/148674985-70f062c2-af62-4d03-8da2-09eec2ee75ee.png)
.

**Comment by AngeLouCN** [comment]
For the CT slice, I think maybe you can consider the preprocessing, more data augmentation and enhancement. Also, you can try to choose only loss5 as loss function without deep supervising.

**Comment by 15104356116** [comment]
Thanks! I'll try it .🥰🥰
