### ISSUE TITLE
About Axial-Attention

### ISSUE THREAD

**Issue by Liqq1** [AngeLouCN/CaraNet#11]
Hi
I notice that the derivation of axial-attention in the code is as follows：
<img width="427" alt="image" src="https://user-images.githubusercontent.com/54054113/155734825-b10d08ab-3c33-48da-abde-09384a482136.png">

But in the original version of axial attention it would look like this：
<img width="405" alt="image" src="https://user-images.githubusercontent.com/54054113/155734867-e1ec5d0e-8412-4ced-b182-8c048f743282.png">
I don't fully understand your code, can you explain it for me?I am looking forward to hearing from u.

**Comment by AngeLouCN** [comment]
Hi, I do not think they are different. There are some other works do the axial-attention in the similar way. 
In this way, we also follow the width to height axis and the output is same as original version. The difference here I think is the size of attention_ map. Due to the limitation of hardware, I need to reduce the parameters.

**Comment by Liqq1** [comment]
I think when axis==‘h’，the code on line 37 should be replaced with ‘projected_query = self.query_conv(x).presume(0,1,3,2).view(*view).permute(0, 2, 1)’
<img width="598" alt="image" src="https://user-images.githubusercontent.com/54054113/155827252-9a0b8a04-1d6c-4c9d-ae6f-1d3673fef7ae.png">
if without presume(0,1,3,2) , h is only the reshape of row 
<img width="972" alt="image" src="https://user-images.githubusercontent.com/54054113/155827259-9ce8e44b-cf83-4b7a-ac18-36745d7c73b4.png">

**Comment by Liqq1** [comment]
Thanks for u reply!
I think when axis==‘h’，the code on line 37 should be replaced with ‘projected_query = self.query_conv(x).presume(0,1,3,2).view(*view).permute(0, 2, 1)’
<img width="559" alt="image" src="https://user-images.githubusercontent.com/54054113/155828403-f4b3ff5d-a6c1-4897-b17c-2f8961ccab76.png">
if without presume(0,1,3,2) , h is only the reshape of row 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/54054113/155828419-f5243a48-c6e8-4179-a4d1-006962bc483f.png">

**Comment by AngeLouCN** [comment]
You can try to add the presume(0,1,3,2). 

Here is what I think. For the axial-attention, we only need to keep those operations are applied at the axis which we need. Like mode = 'h', we only need to care about the **height**. For the output of attention, we only need to make sure the total elements are equal to (batch_size * channel * width * height) and then we can reshape it to (batch_size, channel, width, height).

Also, you can search self attention in Github, you will find some repositories use similar ways to define the **projected_query**
