### ISSUE TITLE
Some questions about self_attn

### ISSUE THREAD

**Issue by Asthestarsfalll** [AngeLouCN/CaraNet#12]
Hi.
1. Why [there](https://github.com/AngeLouCN/CaraNet/blob/2664929e03e1fa8a0763de149b002a573027d547/lib/self_attention.py#L37) is no premute operation before `view` in mode `h`?  
```python
# for mode h
projected_query = self.query_conv(x).premute(0, 1, 3, 2).view(*view).permute(0, 2, 1)
```
2. Why use sigmoid instead of softmax?

**Comment by AngeLouCN** [comment]
Hi, I do not think need premute. For the mode  = 'h', the shape of **projected_query** is **(batch_size, height, channel*weight)**, **projected_key** is **(batch_size, channel*weight, height)**. And the **attention_map** is projected_query * projected_key, and the shape is **(batch_size, height, height)**. The shape of **projected_value** is **(batch_size, channel*weight, height)**. The output is **projected_value * attention_map**, and we reshape the output from **(batch_size, channel*weight, height)** to **(batch_size, channel, weight, height)**. For the mode = 'w' is same. Actually, you may find some repositories, they use the similar way to define self_atten.

For the sigmoid is I find that in our network, sigmoid can get better results

**Comment by Asthestarsfalll** [comment]
I think premute is necessary. Although the shape of those values are correct to calculate，it has a very different meaning for mode h comparing to mode w. Without premute, the `projected_query ` can't actually collect the column to the dimension with size `Hight`
For example:
![05a71f2a6467904872c9ab25a141c6e](https://user-images.githubusercontent.com/72954905/155828961-7fcab4f1-498f-41ca-a635-7bb7eef256f4.png)
![7fd8c2a37637c448a616b22e3780c9a](https://user-images.githubusercontent.com/72954905/155828967-747e3edf-571b-4a00-8e31-e2de737298f3.png)
![14f74a104c974efd101dc50aeb742bc](https://user-images.githubusercontent.com/72954905/155828969-1a1a0d29-b392-4060-a1fe-afeb48f2707f.png)
![16da29c8008298433cae511b9bc0b00](https://user-images.githubusercontent.com/72954905/155828970-176610e1-5238-4e64-9ef7-9e015c38e5c7.png)

**Comment by Asthestarsfalll** [comment]
see [here](https://github.com/plemeri/UACANet/issues/8)
