### ISSUE TITLE
About weighted intersection over union and weighted binary cross-entropy

### ISSUE THREAD

**Issue by maivan-hoa** [AngeLouCN/CaraNet#14]
Hi, thanks for your code!
Can you explain to me why in structure_loss function use weights like this?
`weit = 1 + 5*torch.abs(F.avg_pool2d(mask, kernel_size=31, stride=1, padding=15) - mask)`

**Comment by AngeLouCN** [comment]
Hi, this weights make the loss pay more attention to hard pixel (e.g. boundary). (F.avg_pool2d(mask, kernel_size=31, stride=1, padding=15) - mask) are used to define which pixel are considered as hard one, and then put the weights of those pixels more than one to make network pay attentions at them.

**Comment by maivan-hoa** [comment]
Can you show me FPS when inference model? Thank you!

**Comment by AngeLouCN** [comment]
Hi, I have changed institution and the parts of results are missing. But test FPS is pretty simple and you can follow this link [speed_test](https://github.com/xiaoyufenfei/LEDNet/blob/master/test/eval_forward_time.py), just change the weight, height and number of classes.

**Comment by maivan-hoa** [comment]
Thank you very much. But I want to know CaraNet's FPS number to compare and evaluate with another model I'm building, because I don't have a GPU available and using Colab's GPU gives inaccurate results.

**Comment by AngeLouCN** [comment]
Hi, the speed is about 20 FPS for RTX 2080Ti with image size 352*352.

**Comment by maivan-hoa** [comment]
Thank you very much
