### ISSUE TITLE
About the calculations of the model indicators  of every epoch

### ISSUE THREAD

**Issue by 15104356116** [AngeLouCN/CaraNet#15]
Sorry to bother you. May I ask about how to calculate the IoU, precision, accuracy, recall , and DSC of every epoch? Or what variables should be used to calculate these indicators？I mean ,which variables are TN, FN, TP,FP.Sorry to trouble you!

**Comment by AngeLouCN** [comment]
Hi, there are lots of public codes about the IoU, precision, accuracy, recall, and DSC you can just put them into every epoch training.

**Comment by 15104356116** [comment]
Thanks!
