### ISSUE TITLE
do u do some ablation experments on ur modules

### ISSUE THREAD

**Issue by q671383789** [AngeLouCN/CaraNet#16]
Hi, thanks for ur great work, But I dont see ablation experiments whin ur net, like which part effective the performence more , Do u have done it? I'm very interesting in which modules matters most. thx

**Comment by AngeLouCN** [comment]
Hi, thank you for your interest. We do not do ablation study in this paper. But you can compare our architecture and performance with PraNet. Also, some recent citations of this paper are discussing details about the CFP and A-RA module, may be it will be helpful.

**Comment by q671383789** [comment]
could u please share the names of paper compare about it pls thx





------------------ Original ------------------
From: AngeLouCN ***@***.***&gt;
Date: Fri,May 27,2022 10:49 AM
To: AngeLouCN/CaraNet ***@***.***&gt;
Cc: q671383789 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AngeLouCN/CaraNet] do u do some ablation experments on ur modules (Issue #16)





 
Hi, thank you for your interest. We do not do ablation study in this paper. But you can compare our architecture and performance with PraNet. Also, some recent citations of this paper are discussing details about the CFP and A-RA module, may be it will be helpful.

**Comment by AngeLouCN** [comment]
Hi, you can check those paper. 
An Attention-Preserving Network-Based Method for Assisted Segmentation of Osteosarcoma MRI Images
ColonFormer: An Efficient Transformer based Method for Colon Polyp Segmentation
Attention based multi-scale parallel network for polyp segmentation
