### ISSUE TITLE
binary segmentation

### ISSUE THREAD

**Issue by aram200** [AngeLouCN/CaraNet#18]
Hi, thank you for sharing your code. 
it is really helpful for me 

anyway, i have a question. 
I tried applying your code to my data. My data label values consist of 0,1 .
When applied to this code, the output is 0-255. 
Can you tell me which part needs to be modified to adjust the output value to 0 and 1?
I will wait for your reply. thank you

**Comment by AngeLouCN** [comment]
Hi, thank you for your interest.

I think everything is fine in the Train.py file.
In the Test.py, I use _misc.imsave_ function (**line 67**) to save the output. It automatically convert a [0, 1] output to [0, 255].
Maybe you can change some other save function or divide 255 for output.

**Comment by aram200** [comment]
thanks alot
