### ISSUE TITLE
About the Best modle

### ISSUE THREAD

**Issue by GuoQingqing** [AngeLouCN/CaraNet#2]
Hi, thanks for your code! Did you save an optimal model for every dataset about the polyp segmentation?

**Comment by angelouloveyiyi** [comment]
Hi, I just move to new institution and I can not find the model files. You can train the model for each polyp segmentation dataset, and generally the epoch is less than 100.

**Comment by AngeLouCN** [comment]
Hi, I just move to new institution and I CAN NOT find the model files. However, you can train the model for each polyp segmentation dataset and generally the epoch is less than 100.

**Comment by GuoQingqing** [comment]
> Hi, I just move to new institution and I CAN NOT find the model files. However, you can train the model for each polyp segmentation dataset and generally the epoch is less than 100.

Thanks for your reply! I don't need the modle files.  In your code, I noticed that it seemed like saving a best model for each poplyp testing dataset.  So my question is that, did you train with the same training dataset(five mixed types) and then save an optimal model for each testing set?

**Comment by AngeLouCN** [comment]
> > Hi, I just move to new institution and I CAN NOT find the model files. However, you can train the model for each polyp segmentation dataset and generally the epoch is less than 100.
> 
> Thanks for your reply! I don't need the modle files. In your code, I noticed that it seemed like saving a best model for each poplyp testing dataset. So my question is that, did you train with the same training dataset(five mixed types) and then save an optimal model for each testing set?

Yes! We use same training set and save a model for each testing dataset.

**Comment by GuoQingqing** [comment]
> > > Hi, I just move to new institution and I CAN NOT find the model files. However, you can train the model for each polyp segmentation dataset and generally the epoch is less than 100.
> > 
> > 
> > Thanks for your reply! I don't need the modle files. In your code, I noticed that it seemed like saving a best model for each poplyp testing dataset. So my question is that, did you train with the same training dataset(five mixed types) and then save an optimal model for each testing set?
> 
> Yes! We use same training set and save a model for each testing dataset.

I got it. Thank you very much!
