### ISSUE TITLE
About Query, Key, and Value 

### ISSUE THREAD

**Issue by yushikmr** [AngeLouCN/CaraNet#22]
Hi, 
I'm studying medical segmentation for my job. 
I read your paper and implementation on this repo. 

I have questions about your implementation.  

### Questions

In axial reverse attention module, self attention is use;

https://github.com/AngeLouCN/CaraNet/blob/d64c736f43c2be844a3193dd4e98d9611723a8a7/lib/self_attention.py#L20-L22

I think  Query, Key , and Value in attention modules generally seems to be created by Fully Connected Layer (`nn.Linear`) , But convolutional layers is used in this network.

for example,  ViT repo;

https://github.com/lucidrains/vit-pytorch/blob/4b8f5bc90002a5506d765c811b554760d8dd6ee7/vit_pytorch/vit.py#L47

I'm not a specialist in Transformer, so there are some ideas using convolutional layers for extract Q, K, and V. 

Please tell me about :

- Is the method using  convolutional layers as potential embedding and for extract Q, K, and V popular or adopted DL architecture ?
- The reason why you select not fully connected layers but convolutional layers  for extract Q, K, and V ?

**Comment by AngeLouCN** [comment]
Hi thank you for your interest. In my mind, I think maybe convolutional layer is more convenient in segmentation, like we do not need to flatten the feature maps. You can check out other segmentation works on Github, lots of them use same way to extract Q, K and V.
