### ISSUE TITLE
mean Dice  is greater than 1 when I set --test_path to 'Kvasir' 'CVC-ColonDB' and 'ETIS-LaribPolypDB'

### ISSUE THREAD

**Issue by mingfuyan** [AngeLouCN/CaraNet#24]
Excuse me, mean Dice  is greater than 1 when I set --test_path to './TestDataset/Kvasir' './TestDataset/CVC-ColonDB' and './TestDataset/ETIS-LaribPolypDB'.I don't know why that is.

**Comment by AngeLouCN** [comment]
Hi thank you for your interests. You can modify the **60** in the **Train.py line 78** as the length of dataset's testing set you try.
