### ISSUE TITLE
Sorry to disturb you, I have a little question to ask you. ℒ = ℒ𝐼𝑜𝑈 𝑤 + ℒ𝐵𝐶𝐸 𝑤 to calculate the global loss and local (pixel-level) loss，What do the global loss and local loss mean here ?

### ISSUE THREAD

**Issue by Progressiveyouth** [AngeLouCN/CaraNet#26]

**Comment by AngeLouCN** [comment]
Thank you for your interest in our research. The details of the loss function can be found in our paper "[Pranet](https://link.springer.com/chapter/10.1007/978-3-030-59725-2_26)" in section 2.3, specifically in the "**Loss Function**" subsection.

**Comment by AngeLouCN** [comment]
Thank you for your interest in our research. The details of the loss function can be found in the paper "[Pranet](https://link.springer.com/chapter/10.1007/978-3-030-59725-2_26)" in section 2.3, specifically in the "**Loss Function**" subsection.
