### ISSUE TITLE
About the main.m

### ISSUE THREAD

**Issue by 15104356116** [AngeLouCN/CaraNet#5]
Hi, sorry to bother. I'm wondering  why I got  all the Dice with NaN. I'v check the pathes, but still got NaN in each Dice.
cell. The _result.txt is like 
"(Dataset:CVC-ClinicDB; Model:PraNet) meanDic:NaN;meanIoU:NaN;wFm:NaN;Sm:NaN;meanEm:NaN;MAE:NaN;maxEm:NaN;maxDice:NaN;maxIoU:NaN;meanSen:NaN;maxSen:NaN;meanSpe:NaN;maxSpe:NaN.
"

**Comment by AngeLouCN** [comment]
Hi, I think you should change the model name as 'CaraNet'. As shown in the Test.py, the result are saved in the './results/CaraNet/'

**Comment by 15104356116** [comment]
OMG! Thanks a lot for your reply ！

**Comment by 15104356116** [comment]
By the way, if my data set is MRI , and I change the Traning data to MRI for training, I wonder will the module still work on that ?

**Comment by AngeLouCN** [comment]
I think you need to convert 3-D volume to 2-D slicer and then feed them to network.

**Comment by 15104356116** [comment]
Thank you! 🥰🥰🥰
