### ISSUE TITLE
Fracture segmentation

### ISSUE THREAD

**Issue by andradom** [AngeLouCN/CaraNet#9]
Hi! I am really interested in your proposal and I was wondering if it could fit also bones fracture segmentation tasks. Unfortunately, it seems that it does not perform as expected, with a dice coef of 0.26. Do you have some more insights about the code and what changes may I apply to make your network fit my segmentation problem?

**Comment by AngeLouCN** [comment]
Hi, could you share more information about your task? Like which datasets you use, input size, etc.  

By the way, if you use some other datasets, please be careful about a parameter at **line #78 in Train.py**. You need to change the **60** to the image number of your testing or validation sets.
